### ISSUE TITLE
Don't recommend ``sudo pip install ...``

### ISSUE THREAD

**Issue by adamcik** [hechtus/mopidy-radio-de#1]
To many people will blindly copy such commands, so we shouldn't be encouraging installing pip packages globally. See https://github.com/mopidy/cookiecutter-mopidy-ext/tree/master/%7B%7Bcookiecutter.repo_name%7D%7D for the currently suggested README format.

**Comment by hechtus** [comment]
You mean I should simply remove `sudo`?

**Comment by adamcik** [comment]
Yes, I just ended up with an overly complicated way of saying it.

**Comment by hechtus** [comment]
OK. I will also do this for the Google Music plugin.
