### ISSUE TITLE
Rename to less generic name than mopidy-radio?

### ISSUE THREAD

**Issue by adamcik** [hechtus/mopidy-radio-de#2]
mopidy-radio-de or mopidy-rad-io since I guess this also works for rad.io? Anyway I just suspect mopidy-radio will imply a larger scope than you intended and easily be confused. Of course in the end it's up to you :-)

**Comment by jodal** [comment]
+1

I was just about to report the same issue.

**Comment by hechtus** [comment]
OK. So I will switch to mopidy-rad-io.

**Comment by hechtus** [comment]
Decided for mopidy-radio-de as www.radio.de is the origin of this webservice. See commit 48fdd9b9cd826d59aab2e7ec0edae6413075ff51.

**Comment by hechtus** [comment]
Done, re-release as v0.1.1
