### ISSUE TITLE
missing dependency python-dateutil

### ISSUE THREAD

**Issue by nolyn** [hechtus/mopidy-radio-de#3]
Hi, 

I just installed you extension. I also had to install python-dateutil or it would crash

**Comment by hechtus** [comment]
Thanks for reporting this. This should already have been fixed on the master branch. I added dateutil as a dependency to `setup.py`. I will prepare a new release to fix it on PyPI.

**Comment by hechtus** [comment]
Released 0.1.2 fixing this issue.
